### Combine Temperature and Pressure Data from Scott Base into CSV-File

In [1]:
import pandas as pd
import pytz

In [2]:
temperature_df_6237 = pd.read_csv('../../Data/scottbase/6237__Temperature__daily.csv')
#temperature_df_6237 = temperature_df_6237.iloc[:17000] # Last years seem unreliable
temperature_df_12740 = pd.read_csv('../../Data/scottbase/12740__Temperature__daily.csv')
temperature_df_44557 = pd.read_csv('../../Data/scottbase/44557__Temperature__daily.csv')
temperature_df = pd.concat([temperature_df_6237, temperature_df_12740, temperature_df_44557], ignore_index=True)
temperature_df['DateTime'] = pd.to_datetime(temperature_df['Observation time UTC'])
temperature_df.index = temperature_df['DateTime']
temperature_df.index = temperature_df.index.tz_convert(None)
temperature_df.index = temperature_df.index.floor('D')
temperature_df = temperature_df[~temperature_df.index.duplicated(keep='first')]

temperature_df

,Observation time UTC,Frequency [D/H],Maximum Temperature [Deg C],Data Source (max temp),Minimum Temperature [Deg C],Data Source (min temp),Grass Temperature [Deg C],Data Source (grass temp),Period (max temp),Period (min temp),Period (grass temp),Mean Temperature [Deg C],Period (mean temp),Data Source (mean temp),Mean Relative Humidity [percent],DateTime
DateTime,,,,,,,,,,,,,,,,
1964-09-30,1964-09-30T21:00:00Z,D,NaN,NaN,-28.5,D,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,NaN,1964-09-30 21:00:00+00:00
1964-10-01,1964-10-01T21:00:00Z,D,-21.6,D,-27.6,D,NaN,NaN,24.0,24.0,NaN,-24.6,24.0,D,NaN,1964-10-01 21:00:00+00:00
1964-10-02,1964-10-02T21:00:00Z,D,-21.0,D,-30.6,D,NaN,NaN,24.0,24.0,NaN,-25.8,24.0,D,NaN,1964-10-02 21:00:00+00:00
1964-10-03,1964-10-03T21:00:00Z,D,-21.0,D,-35.6,D,NaN,NaN,24.0,24.0,NaN,-28.3,24.0,D,NaN,1964-10-03 21:00:00+00:00
1964-10-04,1964-10-04T21:00:00Z,D,-21.8,D,-30.5,D,NaN,NaN,24.0,24.0,NaN,-26.2,24.0,D,NaN,1964-10-04 21:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-23,2025-10-23T20:00:00Z,D,-18.2,D,-26.6,D,NaN,NaN,24.0,24.0,NaN,-22.4,24.0,D,50.0,2025-10-23 20:00:00+00:00
2025-10-24,2025-10-24T20:00:00Z,D,-17.0,D,-28.2,D,NaN,NaN,24.0,24.0,NaN,-22.6,24.0,D,53.0,2025-10-24 20:00:00+00:00
2025-10-25,2025-10-25T20:00:00Z,D,-12.9,D,-19.1,D,NaN,NaN,24.0,24.0,NaN,-16.0,24.0,D,42.0,2025-10-25 20:00:00+00:00
2025-10-26,2025-10-26T20:00:00Z,D,-10.1,D,-15.6,D,NaN,NaN,24.0,24.0,NaN,-12.9,24.0,D,60.0,2025-10-26 20:00:00+00:00
2025-10-27,2025-10-27T20:00:00Z,D,-11.3,D,-14.2,D,NaN,NaN,24.0,24.0,NaN,-12.8,24.0,D,65.0,2025-10-27 20:00:00+00:00

In [3]:
#pressure_df_6237 = pd.read_csv('../../Data/scottbase/6237__Pressure__daily.csv')
##pressure_df_6237 = pressure_df_6237.iloc[:17000] # Last years seem unreliable
#
#pressure_df_44557 = pd.read_csv('../../Data/scottbase/44557__Pressure__hourly.csv')
#pressure_df_44557['DateTime'] = pd.to_datetime(pressure_df_44557['Observation time UTC'])
#pressure_df_44557.index = pressure_df_44557['DateTime']
#del pressure_df_44557['DateTime']
#agg_dict = {col: 'mean' if pd.api.types.is_numeric_dtype(dtype) else 'first' for col, dtype in pressure_df_44557.dtypes.items()}
#pressure_df_44557 = pressure_df_44557.resample('1D').agg(agg_dict)
#pressure_df_44557 = pressure_df_44557.reset_index()
#del pressure_df_44557['DateTime']
#
#pressure_df_12740 = pd.read_csv('../../Data/scottbase/12740__Pressure__hourly.csv')
#pressure_df_12740['DateTime'] = pd.to_datetime(pressure_df_12740['Observation time UTC'])
#pressure_df_12740.index = pressure_df_12740['DateTime']
#del pressure_df_12740['DateTime']
#agg_dict = {col: 'mean' if pd.api.types.is_numeric_dtype(dtype) else 'first' for col, dtype in pressure_df_12740.dtypes.items()}
#pressure_df_12740 = pressure_df_12740.resample('1D').agg(agg_dict)
#pressure_df_12740 = pressure_df_12740.reset_index()
#del pressure_df_12740['DateTime']
#
#pressure_df = pd.concat([pressure_df_12740, pressure_df_6237, pressure_df_44557], ignore_index=True)
#pressure_df['DateTime'] = pd.to_datetime(pressure_df['Observation time UTC'])
#pressure_df.index = pressure_df['DateTime']
#pressure_df.index = pressure_df.index.tz_convert(None)
#pressure_df.index = pressure_df.index.floor('D')
#pressure_df = pressure_df[~pressure_df.index.duplicated(keep='first')]
#
#pressure_df

In [4]:
pressure_df_6237 = pd.read_csv('../../Data/scottbase/6237__Pressure__daily.csv')
#pressure_df_6237 = pressure_df_6237.iloc[:17000] # Last years seem unreliable

pressure_df_44557 = pd.read_csv('../../Data/scottbase/44557__Pressure__hourly.csv')
pressure_df_44557['DateTime'] = pd.to_datetime(pressure_df_44557['Observation time UTC'], utc=True)
nz_tz = pytz.timezone('Pacific/Auckland')
pressure_df_44557['DateTime_NZ'] = pressure_df_44557['DateTime'].dt.tz_convert(nz_tz)
pressure_df_44557 = pressure_df_44557[pressure_df_44557['DateTime_NZ'].dt.hour == 9]
pressure_df_44557 = pressure_df_44557.reset_index()
del pressure_df_44557['DateTime']
del pressure_df_44557['DateTime_NZ']

pressure_df_12740 = pd.read_csv('../../Data/scottbase/12740__Pressure__hourly.csv')
pressure_df_12740['DateTime'] = pd.to_datetime(pressure_df_12740['Observation time UTC'], utc=True)
nz_tz = pytz.timezone('Pacific/Auckland')
pressure_df_12740['DateTime_NZ'] = pressure_df_12740['DateTime'].dt.tz_convert(nz_tz)
pressure_df_12740 = pressure_df_12740[pressure_df_12740['DateTime_NZ'].dt.hour == 9]
pressure_df_12740 = pressure_df_12740.reset_index()
del pressure_df_12740['DateTime']
del pressure_df_12740['DateTime_NZ']

pressure_df = pd.concat([pressure_df_12740, pressure_df_6237, pressure_df_44557], ignore_index=True)
pressure_df['DateTime'] = pd.to_datetime(pressure_df['Observation time UTC'])
pressure_df.index = pressure_df['DateTime']
pressure_df.index = pressure_df.index.tz_convert(None)
pressure_df.index = pressure_df.index.floor('D')
pressure_df = pressure_df[~pressure_df.index.duplicated(keep='first')]

pressure_df

,index,Observation time UTC,Data Source (station level pressure),Mean sea level pressure [Hpa],Station level pressure,Data Source (mean sea level pressure),DateTime
DateTime,,,,,,,
2001-01-11,12.0,2001-01-11T20:00:00Z,H,998.0,995.4,H,2001-01-11 20:00:00+00:00
2001-01-12,36.0,2001-01-12T20:00:00Z,H,1002.2,999.6,H,2001-01-12 20:00:00+00:00
2001-01-13,60.0,2001-01-13T20:00:00Z,H,999.9,997.3,H,2001-01-13 20:00:00+00:00
2001-01-14,84.0,2001-01-14T20:00:00Z,H,993.5,990.9,H,2001-01-14 20:00:00+00:00
2001-01-15,107.0,2001-01-15T20:00:00Z,H,995.0,992.4,H,2001-01-15 20:00:00+00:00
...,...,...,...,...,...,...,...
2025-09-24,41916.0,2025-09-24T21:00:00Z,H,991.4,985.8,H,2025-09-24 21:00:00+00:00
2025-09-25,41940.0,2025-09-25T21:00:00Z,H,994.4,988.8,H,2025-09-25 21:00:00+00:00
2025-09-26,41964.0,2025-09-26T21:00:00Z,H,990.1,984.6,H,2025-09-26 21:00:00+00:00
2025-09-27,41987.0,2025-09-27T20:00:00Z,H,993.1,987.3,H,2025-09-27 20:00:00+00:00
2025-09-28,42011.0,2025-09-28T20:00:00Z,H,997.7,992.0,H,2025-09-28 20:00:00+00:00

In [5]:
TP = pd.concat([temperature_df['Mean Temperature [Deg C]'], pressure_df['Mean sea level pressure [Hpa]']], axis=1)
TP

            Mean Temperature [Deg C]  Mean sea level pressure [Hpa]
DateTime
1964-09-30                       NaN                         1005.0
1964-10-01                     -24.6                          997.6
1964-10-02                     -25.8                          997.4
1964-10-03                     -28.3                          989.1
1964-10-04                     -26.2                          976.2
...                              ...                            ...
2025-10-23                     -22.4                            NaN
2025-10-24                     -22.6                            NaN
2025-10-25                     -16.0                            NaN
2025-10-26                     -12.9                            NaN
2025-10-27                     -12.8                            NaN

[22306 rows x 2 columns]

In [6]:
TP.to_csv('../../Data/scottbase/scottbase.csv')